name: 'Teams Notifier'
description: 'Send a Microsoft Teams notification'
inputs:
  notification_title:
    required: true
  action_required_message:
    required: false
    default: '⚠️ Action Required'
  card_color:
    required: false
    default: 'Accent'
  files:
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run Teams Notification Script
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/goodbye.sh
        $GITHUB_ACTION_PATH/goodbye.sh \
          "${{ inputs.notification_title }}" \
          "${{ inputs.action_required_message }}" \
          "${{ inputs.card_color }}" \
          "${{ inputs.files }}"
